package events

import (
	"SysmonSimulator/cmd/utilities"
	"fmt"
	"log"
	"os"
	"os/exec"
	"time"
)

func FileCreationTimeChanged() {
	// Create a new file with a random hex title
	targetFileName := fmt.Sprintf("C:\\Windows\\Temp\\KnightChaser-%s.exe", utilities.GenerateRandomHex(20))
	err := os.WriteFile(targetFileName, []byte("SysmonSimulator :D"), 0644)
	if err != nil {
		log.Panicf("[-] Error while creating a new file: %v\n", err)
		return
	}

	// Modify the file creation time
	currentTime := time.Now().Local().Format("2006-01-02 15:04:05")
	modifiedTime := "2222-09-26 11:11:11"
	powershellCommand := exec.Command("powershell", "-command", fmt.Sprintf("(Get-Item '%s').CreationTime=('%s')", targetFileName, modifiedTime))
	if err := powershellCommand.Run(); err != nil {
		log.Panicf("[-] Error while modifying the file creation time: %v\n", err)
		return
	}

	log.Printf("[+] Target Filename: %s\n", targetFileName)
	log.Printf("[+] Creation time modified: %s → %s\n", currentTime, modifiedTime)
	log.Printf("[+] Check Sysmon event id 2 with name of PowerShell.exe because this event is generated by the powershell command\n")

	// Clean up the file
	err = os.Remove(targetFileName)
	if err != nil {
		log.Panicf("[-] Error while removing the file: %v\n", err)
		return
	}
}
